DIALOG MAINDIALOG
{
    NAME MAINDIALOG_STR;    
    
    GROUP
    {
        BORDERSIZE 4,4,4,4;
        
        CENTER_H;
        
        COLUMNS 1;
        SCALE_H; 
          
        GROUP
        {
            COLUMNS 1;
            SCALE_H; 
			BORDERSTYLE BORDER_THIN_IN; BORDERSIZE 14, 14, 14, 14; 
        GROUP
        {
					COLUMNS 2;
					SCALE_H; 
			GROUP
			{
				NAME GRP_GENERAL ;
				COLUMNS 1;
				SCALE_H; 
				SCALE_V; 
					BORDERSTYLE BORDER_THIN_IN; BORDERSIZE 14, 14, 14, 14; 
			  
				GROUP
				{
					COLUMNS 2;
					SCALE_H; 
					SCALE_V; 
					SIZE 300, 0;
					
					STATICTEXT REAL_SCALE_STR { NAME REAL_SCALE_STR;SIZE 100, 0; }
					EDITNUMBERARROWS REAL_SCALE {SCALE_H;}	
				}
				CHECKBOX CBOX_DEBUG { NAME CBOX_DEBUG;SCALE_H; ALIGN_BOTTOM;}
				CHECKBOX CBOX_CLOSEAFTER { NAME CBOX_CLOSEAFTER;SCALE_H;ALIGN_BOTTOM; }

		} 
          	GROUP
				{
					NAME GRP_SKELETONANIMATIONS ;
					COLUMNS 1;
					SCALE_H; 
					BORDERSTYLE BORDER_THIN_IN; BORDERSIZE 14, 14, 14, 14; 
					
					GROUP
					{
						COLUMNS 2;
						SCALE_H; 
						SCALE_V; 
						SIZE 300, 0;
						
						STATICTEXT REAL_SCALE_JOINTS_STR { NAME REAL_SCALE_JOINTS_STR;SIZE 150, 0; }
						EDITNUMBERARROWS REAL_SCALE_JOINTS {SCALE_H;}	
					}
					CHECKBOX CBOX_SKEL_ANIM_TRANSLATIONS { NAME CBOX_SKEL_ANIM_TRANSLATIONS;SCALE_H; }
					CHECKBOX CBOX_SKEL_ROOT_ANIM_TRANSLATIONS { NAME CBOX_SKEL_ROOT_ANIM_TRANSLATIONS;SCALE_H; }
					CHECKBOX CBOX_SKEL_ANIM_SCALE { NAME CBOX_SKEL_ANIM_SCALE;SCALE_H; }
					CHECKBOX CBOX_SKEL_ROOT_ANIM_SCALE { NAME CBOX_SKEL_ROOT_ANIM_SCALE;SCALE_H; }
				
				} 

		} 
				GROUP
				{
					NAME GRP_TEXTURES;
					COLUMNS 1;
					SCALE_H; 
					BORDERSTYLE BORDER_THIN_IN; BORDERSIZE 14, 14, 14, 14; 
					
					GROUP
					{
						SCALE_H; 
						COLUMNS 2;
						STATICTEXT COMBO_EXTERNTEXTURESPATH_STR { NAME COMBO_EXTERNTEXTURESPATH_STR;SIZE 250, 0; }
						COMBOBOX COMBO_EXTERNTEXTURESPATH {ALIGN_TOP; ALIGN_LEFT;SCALE_H; SIZE 250, 0;CHILDS 
										{
											0, COMBOITEM_AWDFILE;
											1, COMBOITEM_GLOBAL;
											2, COMBOITEM_OTHER;
										} }  
					}
					FILENAME LINK_EXTERNTEXTURESPATH { SIZE 250, 0; DIRECTORY;}
					GROUP
					{
						SCALE_H; 
						COLUMNS 2;
						STATICTEXT COMBO_EMBEDTEXTRESPATH_STR { NAME COMBO_EMBEDTEXTRESPATH_STR;SIZE 250, 0; }
						COMBOBOX COMBO_EMBEDTEXTRESPATH {ALIGN_TOP; ALIGN_LEFT;SCALE_H;SIZE 250, 0; CHILDS 
										{
											0, COMBOITEM_AWDFILE;
											1, COMBOITEM_C4DFILE;
											2, COMBOITEM_C4DFILETEX;
											3, COMBOITEM_OTHER;
										} }  
					}
					FILENAME LINK_EMBEDTEXTRESPATH { SIZE 250, 0; DIRECTORY;}

				}     
        }

	
        GROUP
        {
            COLUMNS 1;
            SCALE_H; 
          
            BUTTON BTN_IMPORT { NAME BTN_IMPORT;SIZE 200, 30;SCALE_H; }
            
            
        }
       
        SEPARATOR { SCALE_H; }
			GROUP
			{
				COLUMNS 1;
				SCALE_H; 
				STATICTEXT STRING_80PRO { NAME STRING_80PRO;SCALE_H; CENTER_H;CENTER_V; }
			
			}    
    
    }
}