CONTAINER AWDSkeletonTag
{
	NAME AWDSkeletonTag;

	GROUP 
	{
		BOOL AWDSKELETON_EXPORT{}
		STRING AWDSKELETON_NAME { }
		BOOL AWDSKELETON_EXPORTSCENEOBJECTS{}
	    SEPARATOR { SCALE_H; }
		BUTTON AWDSKELETON_CREATEPOSETAG{} 
	    SEPARATOR { SCALE_H; }          
		BUTTON AWDSKELETON_JPP_CHECK{}
	    SEPARATOR { SCALE_H; }
		BUTTON AWDSKELETON_JPP_REDUCE{}
	    SEPARATOR { SCALE_H; }
	GROUP 
	{
        
		NAME AWDSKELETON_TAGS;
		SCALE_V;
	    SEPARATOR { SCALE_H; }
	GROUP
	{
		COLUMNS 3;   
		BOOL AWDSKELETON_JPP_REDUCE1{}
		LINK AWDSKELETON_JPP_LINK1{}  
        STRING AWDSKELETON_JPP_TEXT1{}  
	}
	    SEPARATOR { SCALE_H; }
	GROUP
	{
		COLUMNS 3;  
		BOOL AWDSKELETON_JPP_REDUCE2{}
		LINK AWDSKELETON_JPP_LINK2{} 
        STRING AWDSKELETON_JPP_TEXT2{}   
	}
	    SEPARATOR { SCALE_H; }
	GROUP
	{
		COLUMNS 3;   
		BOOL AWDSKELETON_JPP_REDUCE3{}
		LINK AWDSKELETON_JPP_LINK3{}   	
        STRING AWDSKELETON_JPP_TEXT3{}  
	}
	    SEPARATOR { SCALE_H; }	
	GROUP
	{
		COLUMNS 3;  
		BOOL AWDSKELETON_JPP_REDUCE4{}
		LINK AWDSKELETON_JPP_LINK4{}  
        STRING AWDSKELETON_JPP_TEXT4{}   
	}
	    SEPARATOR { SCALE_H; }		
	GROUP
	{
		COLUMNS 3;  
		BOOL AWDSKELETON_JPP_REDUCE5{}
		LINK AWDSKELETON_JPP_LINK5{}  
        STRING AWDSKELETON_JPP_TEXT5{}   
	}
	    SEPARATOR { SCALE_H; }
	GROUP
	{
		COLUMNS 3;  
		BOOL AWDSKELETON_JPP_REDUCE6{}
		LINK AWDSKELETON_JPP_LINK6{} 
        STRING AWDSKELETON_JPP_TEXT6{}   
	}
	    SEPARATOR { SCALE_H; }	
	GROUP
	{
		COLUMNS 3;  
		BOOL AWDSKELETON_JPP_REDUCE7{}
		LINK AWDSKELETON_JPP_LINK7{}  
        STRING AWDSKELETON_JPP_TEXT7{}   
	}
	    SEPARATOR { SCALE_H; }	
	GROUP
	{
		COLUMNS 3; 
		BOOL AWDSKELETON_JPP_REDUCE8{}
		LINK AWDSKELETON_JPP_LINK8{}  
        STRING AWDSKELETON_JPP_TEXT8{}    
	}
	    SEPARATOR { SCALE_H; }	
	GROUP
	{
		COLUMNS 3;  
		BOOL AWDSKELETON_JPP_REDUCE9{}
		LINK AWDSKELETON_JPP_LINK9{}   
        STRING AWDSKELETON_JPP_TEXT9{}   
	}
	    SEPARATOR { SCALE_H; }	
	GROUP
	{
		COLUMNS 3;  
		BOOL AWDSKELETON_JPP_REDUCE10{}
		LINK AWDSKELETON_JPP_LINK10{}  
        STRING AWDSKELETON_JPP_TEXT10{}   
	}
	}
    } 		
}
