CONTAINER AWDAnimator
{
    NAME AWDAnimator;

    GROUP 
    {  
        BOOL ANIMATOR_EXPORT{}
        STRING ANIMATOR_NAME {}
        LINK LINK_TARGETOBJ{}
        LINK LINK_TARGETSTATE{}
        LINK LINK_SKELETON{}
	}

}